
version: '3.8'

services:
  app1:
    build:
      context: .
      dockerfile: Dockerfile.app1
    ports:
      - "5000:5000"
    networks:
      - my-network

  app2:
    build:
      context: .
      dockerfile: Dockerfile.app2
    ports:
      - "5001:5001"
    networks:
      - my-network

networks:
  my-network:
    driver: bridge