FROM alpine:latest

RUN apk update
RUN apk add python3 py3-pip
RUN pip3 install flask requests --break-system-packages
RUN mkdir /app
COPY ./app2.py /app/app.py

CMD ["python3", "/app/app.py", "--host=0.0.0.0", "--port=5001"]